# Generated by Django 4.0.2 on 2022-05-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='skill',
            name='unique skill',
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('name', 'portfolio'), name='unique skill'),
        ),
    ]
